name: Build

on:
  push:
  pull_request:
  schedule:
    # runs the CI everyday at 10AM
    - cron: "0 10 * * *"

jobs:
  flutter:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        channel:
          - dev
          - stable

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ matrix.package }}

      - name: Check format
        run: flutter format --set-exit-if-changed .
        working-directory: ${{ matrix.package }}

      - name: Analyze
        run: flutter analyze
        working-directory: ${{ matrix.package }}

      - name: Run tests
        run: flutter test --coverage
        working-directory: ${{ matrix.package }}

      - name: Upload coverage to codecov
        run: curl -s https://codecov.io/bash | bash